[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ftouter"
version = "0.1.1"
description = "A resilient runtime layer for free/cheap-tier LLM APIs"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [{name = "Irfan", email = "youcanbet5@gmail.com"}]
dependencies = [
    "requests",
    "python-dotenv",
]

[project.urls]
Homepage = "https://github.com/Irfan-gitt/LLM-Router"
Repository = "https://github.com/Irfan-gitt/LLM-Router"

[tool.setuptools.packages.find]
include = ["ftouter*"]